### PR TITLE
fix(vite-plugin): can't assign port

### LINKED ISSUE #527: Can't assign port
**Describe the bug**

Normally, you can overwrite the port in the `vite.config.ts` file with

```
export default defineConfig({
  plugins: [motionCanvas()],
  server: {
    port: 3000
  }
});
```

Or just run `vite --port 3000`

But that doesn't work and always starts on port 9000

**To Reproduce**

Just follow the instructions

**Expected behavior**

The application runs on port 3000

**Package versions (please complete the following information):**

- core: ^3.2.0
- ui: ^3.2.1

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
closes #527

### CODE REVIEW

File: packages/vite-plugin/src/main.ts [hunk 1]
```diff
@@ -384,7 +384,7 @@ export default ({
           },
         },
         server: {
-          port: 9000,
+          port: config?.server?.port || 9000,
```
Comment (aarthificial) [inline packages/vite-plugin/src/main.ts:387]: We should use nullish coalescing whenever applicable:
```suggestion
          port: config?.server?.port ?? 9000,
```
I know the port can't be `0` in this specific case but `??` better conveys the meaning of the code (if `port` is not defined, use `9000`)

**Review by aarthificial — CHANGES_REQUESTED** [review]

**Review by aarthificial — APPROVED** [review]

**Comment by aarthificial** [comment]
Awesome, thanks!
